[project]
name = "worker"
version = "0.0.0"
requires-python = "~=3.14.0"
dependencies = ["core", "dtos"]

[dependency-groups]
dev = []

[build-system]
requires = ["uv_build>=0.10.2,<0.11.0"]
build-backend = "uv_build"
