[project]
name = "api"
version = "0.0.0"
requires-python = "~=3.14.0"
dependencies = [
    "core",
    "fastapi ~= 0.112",
    "pydantic ~= 2.8",
    "uvicorn ~= 0.27",
]

[dependency-groups]
dev = ["httpx"]

[build-system]
requires = ["uv_build>=0.10.2,<0.11.0"]
build-backend = "uv_build"
